domain: "{{ vault_domain }}"
internal_subdomain: internal
inernal_domain: "{{ internal_subdomain }}.{{ domain }}"

timezone: Europe/Berlin

ssh_port: "{{ vault_ssh_port }}"
ansible_port: "{{ ssh_port }}"
