- name: Create and start openldap container
  community.docker.docker_compose_v2:
    project_src: "{{ openldap_app_dir }}"
    state: present
    recreate: always
  register: output
  listen: "Restart Openldap"
  when: not ansible_check_mode

- name: Check that all containers are running
  ansible.builtin.assert:
    that:
      - openldap.State == 'running'
  vars:
    openldap: >-
      {{ output.containers | selectattr("Service", "equalto", "openldap") | first }}
  listen: "Restart Openldap"
  when: not ansible_check_mode
